# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'InnerSource Commons'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'The journey is the reward'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: 'InnerSource applies the lessons of Open Source to all software engineering, using collaboration and transparency to increase quality, speed, and developer joy'

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Maintained by the InnerSource community. InnerSourceCommons.org site content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA</a> license unless otherwise marked.</p>'

# Main author of the website
# See > authors.yml
author: cewilliams

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: ''
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/InnerSourceCommons/innersourcecommons.org/edit/master

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://innersourcecommons.org/images/'


# Logo size is 600x80 pixels
logo: "isc-border.png"


#       ____              _             __  _
#      / __ \____ _____ _(_)___  ____ _/ /_(_)___  ____
#     / /_/ / __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
#    / ____/ /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
#   /_/    \__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
#               /____/
#
plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-redirect-from
#paginate: 5                      # Paginates all X entries
#paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work




# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - cibuild
    # exclude copying modules from travis build
    - vendor
    
# The language setting is used in /includes/header.html for html-settings
language: 'en'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      sidebar: left   		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: cewilliams     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      sidebar: left       # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: cewilliams     # Default author for posts



#       _   __            _             __  _
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/
#                       /____/
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

# google_author:             'https://plus.google.com/u/0/118311555303973066167'
# google_site_verification:  'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
# bing_webmastertools_id:    '0FB4C028ABCF07C908C54386ABD2D97F'
# alexa_verify_id:         ''



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'isc-logo-192.png'
apple-touch-icon-180x180-precomposed:   'isc-logo-180.png'
apple-touch-icon-152x152-precomposed:   'isc-logo-152.png'
apple-touch-icon-144x144-precomposed:   'isc-logo-144.png'
apple-touch-icon-120x120-precomposed:   'isc-logo-120.png'
apple-touch-icon-114x114-precomposed:   'isc-logo-114.png'
apple-touch-icon-76x76-precomposed:     'isc-logo-76.png'
apple-touch-icon-72x72-precomposed:     'isc-logo-72.png'
apple-touch-icon-precomposed:           'logo.png'
msapplication_tileimage:                'isc-logo-144.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'


#       ______                __                __
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

# og_image:                           'http://images.phlow.de/phlow/phlow_de-logo-512x.png'
# og_locale:                          'en_EN'
# og_type:                            'website'


#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#

socialmedia:
#     twitter: PayPalFLOW
#     facebook: phlow.media


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments

# disqus_shortname: feelingresponsive


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

# google_analytics_tracking_id: UA-60112281-1



#   _                 _     _
#  | |_ __ ___      _| | __| |_ ___
#  | __/ _` \ \ /\ / / |/ /| __/ _ \
#  | || (_| |\ V  V /|   < | || (_) |
#   \__\__,_| \_/\_/ |_|\_(_)__\___/     More › https://www.tawk.to/knowledgebase/
#
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:
